FROM microsoft/aspnetcore-build:2
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src
COPY my-dotnet-sln.sln .
COPY backend/backend.csproj backend/
COPY sharedlib/sharedlib.csproj sharedlib/
RUN dotnet restore backend/backend.csproj
COPY . .
WORKDIR backend
RUN dotnet build

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]